# Generated by Django 3.1.7 on 2021-03-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasktracker_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktracker',
            name='task',
        ),
        migrations.AddField(
            model_name='tasktracker',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Task Type 1'), (2, 'Task Type 2'), (3, 'Task Type 3')], default=1),
            preserve_default=False,
        ),
    ]
